import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css';
import Navbar from './components/Navbar';



const lato = Poppins({ weight:'400',subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Copyforest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
